runtime: python:3.12 # Ensure the runtime version matches the Python version your app requires

app_name: FinalCloudAssignment36 # Replace with your app's name

# Command to run your app
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app

# Environment variables for your app
env:
  FLASK_ENV: production # Set the Flask environment to production
  # DATABASE_URL: <your_database_url>  # Add your database URL if applicable
  # SECRET_KEY: <your_secret_key>      # Add a secret key for Flask-WTF forms if required

# Script to install dependencies
dependencies:
  - pip install -r requirements.txt # Ensure the correct dependencies are installed

# Additional configurations (if required)
resources:
  cpu: 1
  memory: 1Gi

logs:
  level: info # Configure log level